name: btc_price_app
description: BTC 가격 조회 앱
publish_to: "none"

version: 3.0.12+12

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 상태관리
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # API 통신
  dio: ^5.4.1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1

  # 유틸리티
  freezed_annotation: ^2.4.1
  intl: any

  # 추가
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  firebase_messaging: ^15.1.0
  firebase_core: ^3.4.0
  flutter_local_notifications: ^17.2.2
  google_mobile_ads: ^5.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  firebase_crashlytics: ^4.1.0
  firebase_analytics: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # 코드 생성
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  # 추가
  assets:
    - .env
    - assets/lang/
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  # 스플래시 화면의 배경색
  color: "#000000"
  color_dark: "#000000"

  # 스플래시 화면에 표시할 이미지를 설정 (앱 아이콘, 로고 등)
  image: assets/icon/icon.png

  # Android 12용 세부 설정 (Map 형태로 작성)
  android_12:
    # Android 12에서 사용할 스플래시 배경색
    color: "#000000"
    color_dark: "#000000"
    # Android 12에서 사용할 스플래시 아이콘 (선택)
    image: assets/icon/icon.png
    # 필요 시 branding, fullscreen, image_dark 등 다양한 옵션 사용 가능

  # 안드로이드에서 이미지의 배치 위치
  android_gravity: center

  # iOS에서 이미지의 표시 모드 (중앙 정렬)
  ios_content_mode: center

  # 안드로이드/아이폰 플랫폼 모두 생성
  android: true
  ios: true
